### PR TITLE
Deprecate Notebook Submit Form Button Fix

### LINKED ISSUE #333: Deprecate notebook form is wonky regarding submit button
On initial load, the submit button is clickable (not disabled) despite form not being filled out.

The optional field (alternate notebooks) isn't optionable until you click on it and then exit out of the autocomplete popup.

### PR DESCRIPTION
**Pull request by manfromjupyter**
Closes #333

### CODE REVIEW

File: app/assets/javascripts/notebook_actions.js.erb [hunk 1]
```diff
@@ -569,7 +570,12 @@ $(document).ready(function(){
     });
     return false;
   });
+  // Disable/Enable hack for submit button. Remove once over to Rails 5, is default behavior in 5.
+  if ($('#deprecateNotebookReasoning').value == null) {
+    $('#deprecateNotebookSubmit').attr('disabled', true);
+  }
   $('#deprecateNotebookReasoning').keyup(function(){
+    $('#deprecateNotebookSubmit').attr('disabled', false);
```
Comment (mcrutch) [inline app/assets/javascripts/notebook_actions.js.erb:578]: This does not verify that there is actual content in the box, just that a key was pressed and released.  Press an arrow key and release, and it still activates the deprecate button.

**Comment by manfromjupyter** [comment]
@mcrutch Requires 3 of more characters now. Browser will enforce it and inform the user why submit is disabled (if they are under that 3 character minimum.

deprecate modal on blank
deprecate modal under 3 characters
deprecate modal characters remaining
deprecate modal out of characters
